FROM rust:latest
WORKDIR /app

COPY Cargo.toml Cargo.lock ./

RUN apt-get update && apt-get install -y iputils-ping procps libcap2-bin && rm -rf /var/lib/apt/lists/*

RUN mkdir -p src && echo "fn main(){}" > src/main.rs
RUN cargo build --release

RUN rm -rf src

COPY . .

RUN cargo build --release

RUN useradd -m -u 1000 appuser && chown -R appuser:appuser /app
RUN setcap 'cap_net_bind_service=+ep' /app/target/release/counter-app
USER appuser

EXPOSE 80
CMD ["./target/release/counter-app"]