FROM rust:latest
WORKDIR /app

COPY Cargo.toml Cargo.lock ./

RUN mkdir -p src && echo "fn main(){}" > src/main.rs
RUN cargo build --release

RUN rm -rf src

COPY . .

RUN cargo build --release

EXPOSE 3000
CMD ["./target/release/counter-app"]